config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/calendar' => 'events#index'

  resources :events, only: [:index, :show, :new, :create, :edit, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
require 'pry'

class EventsController < ApplicationController

  def index
    @events = Event.all
    if params[:date]
      @selected = params[:date]
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new()
  end

  def create
    @event = Event.new(event_params)
    find_event = Event.find_by(time: @event.time)
    if find_event.present?
      flash[:notice] = "There is already an event at this time. Find another time."
      redirect_to new_event_path
    else
      @event.save
      redirect_to events_path
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:id])
    @event.delete
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :time)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/edit.html.slim
doctype html
html
  head
  body
  = form_for @event, method: :patch do |f|
    = f.label :event_name
    = f.text_field :name
    = f.label :event_time
    = f.datetime_select(:time, :include_seconds => true)
    = f.submit

app/views/events/index.html.slim
doctype html
html
  head
    meta name="keywords" content="template language"
    script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"/

  body
    coffee:
      $ ->
        console.log("DOM is ready")

    - if @selected == nil
      h1 Pick a Month and Year to View Your Calendar
    = form_tag events_path, method: :get
      = select_month(Date.today)
      = select_year(Date.today)
      = submit_tag "Submit"
    - if @selected != nil
      - month = @selected["month"].to_i
      - year = @selected["year"].to_i
      - month_string = Date.new(year, month, 1).strftime("%B")
      h1 #{month_string} #{year}
      p Edit Events:
      table
        thead
          - beginning_of_month = Date.civil(year, month ,1)
          - end_of_month = Date.civil(year, month , -1)
          - month_array = (beginning_of_month..end_of_month).map {|day| day}
          - if month_array[0].strftime("%A") == "Monday"
            - month_array.unshift(" ")
          - elsif month_array[0].strftime("%A") == "Tuesday"
            - month_array.unshift(" ", " ")
          - elsif month_array[0].strftime("%A") == "Wednesday"
            - month_array.unshift(" ", " ", " ")
          - elsif month_array[0].strftime("%A") == "Thursday"
            - month_array.unshift(" ", " ", " ", " ")
          - elsif month_array[0].strftime("%A") == "Friday"
            - month_array.unshift(" ", " ", " ", " ", " ")
          - elsif month_array[0].strftime("%A") == "Saturday"
            - month_array.unshift(" ", " ", " ", " ", " ", " ")
          - weeks = month_array.each_slice(7).to_a

          tr
            th Sunday
            th Monday
            th Tuesday
            th Wednesday
            th Thursday
            th Friday
            th Saturday

        tbody
          - weeks.each do | week |
            tr
              - week.each do | day |
                - $event_text
                - day_id = "d" + day.to_s
                - date = day.to_s
                - day_events = @events.select do | event |
                  - event.time.month.to_s.length == 1 ? month = "0"+event.time.month.to_s : month = event.time.month.to_s
                  - event.time.day.to_s.length == 1 ? day = "0"+event.time.day.to_s : day = event.time.day.to_s
                  - event_time = "d" + event.time.year.to_s + "-" + month + "-" + day
                  - day_id == event_time
                - print_events = day_events.collect do | event |
                  - find_event = Event.find(event.id)
                  - link_to "#{event.name}", event_path(find_event)
                - print_events.each do |event|
                  div class="edit" #{event}
                - names = day_events.sort.collect do | event |
                  - time = event.time.strftime("%l:%M %p")
                  - time + ": " + event.name
                td id="#{day_id}" #{date} #{names}

      = link_to 'Create an Event', new_event_path

app/views/events/new.html.slim
doctype html
html
  head
  body
  = form_for @event, method: :post do |f|
      = f.label :event_name
      = f.text_field :name
      = f.label :event_time
      = f.datetime_select(:time, :include_seconds => true)
      = f.submit

app/views/events/show.html.slim
doctype html
html
  head
    meta name="keywords" content="template language"
  body
    h1 Event: #{@event.name}
    h2 Time: #{@event.time.strftime("%A, %b %d %l:%M %p")}
    = link_to 'Edit Event', edit_event_path(@event)
    br
    = link_to 'Delete Event', event_path(@event),  method: :delete, remote: true
    br
    = link_to 'Back to Calendar', events_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonthlyCalendarApplication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>